flags:
 ls: flag
 cd: flag
 pwd: flag
 hierarchy: flag
 mkdir: flag
 cat: flag
 man: flag
 users: flag
 whoami: flag
 su: flag
 chown: flag
 sudo: flag
 exec-files: flag
 base64: flag
 pipe: flag
 echo: flag
 grep: flag
 zip: flag
 tar: flag
